export const SHOW_MODAL = "SHOW_MODAL";

export const HIDE_MODAL = "HIDE_MODAL";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const SET_EN_LOCALE = "SET_EN_LOCALE";

export const SET_FR_LOCALE = "SET_FR_LOCALE";

export const SET_ES_LOCALE = "SET_ES_LOCALE";

export const FETCH_OPERATIONS = "FETCH_OPERATIONS";

export const SHOW_ACTIVITIES_NEWS = "SHOW_ACTIVITIES_NEWS";

export const SHOW_ACTIVITIES_BALANCE = "SHOW_ACTIVITIES_BALANCE";

export const SET_PHONE_RESTORATION = "SET_PHONE_RESTORATION";

export const SET_CHATBOT_COMPLETED = "SET_CHATBOT_COMPLETED";

export const SET_SELECTED_CHART_ELEMENT = "SET_SELECTED_CHART_ELEMENT";

export const PARSE_CURRENT_ERROR = "PARSE_CURRENT_ERROR";

export const CLEAR_CURRENT_ERROR = "CLEAR_CURRENT_ERROR";

export const SET_USER_ID = "SET_USER_ID";

export const SET_PROFILE_BALANCE = "SET_PROFILE_BALANCE";

export const SET_REG_TYPE = "SET_REG_TYPE";
